### ISSUE TITLE
安装时候php报错

### ISSUE THREAD

**Issue by purevirtual** [guanguans/dnmp-plus#13]
**Describe the bug**
安装时候php报错

**To Reproduce**
docker-compose up -d php72 nginx mysql mongo1. Go to '...'
显示 ERROR: Service 'php72' failed to build: Please provide a source image with `from` prior to commit

**Expected behavior**
没法正常运行了

**Screenshots**

**Additional context**

**Comment by guanguans** [comment]
@purevirtual 更新一下 docker 版本，这边测试是没问题的，[测试详情](https://travis-ci.org/github/guanguans/dnmp-plus/builds/702260890)。

**Comment by purevirtual** [comment]
> @purevirtual 更新一下 docker 版本，这边测试是没问题的，[测试详情](https://travis-ci.org/github/guanguans/dnmp-plus/builds/702260890)。

感谢 确实是这个问题 yum里面的docker版本比较老了 直接下了个最新的解决问题
