### ISSUE TITLE
子模组 'www/xhgui-branch'（https://github.com/laynefyc/xhgui-branch.git）未对路径 'www/xhgui-branch' 注册

### ISSUE THREAD

**Issue by TimeIsGoOn** [guanguans/dnmp-plus#16]
本机系统是ubuntu

sun@sun-T58-D:~/learn$  git clone https://github.com/guanguans/dnmp-plus.git --recursive
正克隆到 'dnmp-plus'...
remote: Enumerating objects: 294, done.
remote: Total 294 (delta 0), reused 0 (delta 0), pack-reused 294
接收对象中: 100% (294/294), 6.46 MiB | 26.00 KiB/s, 完成.
处理 delta 中: 100% (137/137), 完成.
子模组 'www/xhgui-branch'（https://github.com/laynefyc/xhgui-branch.git）未对路径 'www/xhgui-branch' 注册
正克隆到 '/home/sun/learn/dnmp-plus/www/xhgui-branch'...
remote: Enumerating objects: 5350, done.        
remote: Total 5350 (delta 0), reused 0 (delta 0), pack-reused 5350        
接收对象中: 100% (5350/5350), 2.22 MiB | 17.00 KiB/s, 完成.
处理 delta 中: 100% (3047/3047), 完成.
子模组路径 'www/xhgui-branch'：检出 '034175ee593954d08b58c2667004532d8ab0822c'

![image](https://user-images.githubusercontent.com/13595639/92080310-ec914280-edf3-11ea-98ef-c5ec57195ad6.png)

sun@sun-T58-D:~/learn$ cd dnmp-plus/
sun@sun-T58-D:~/learn/dnmp-plus$ ls

conf  _config.yml  docker-compose-sample.yml  Dockerfile  docs  env.sample  extensions  LICENSE  log  mongo  mysql  README-EN.md  README.md  travis-build.sh  www

sun@sun-T58-D:~/learn/dnmp-plus$ cp env.sample env
sun@sun-T58-D:~/learn/dnmp-plus$ cp docker-compose-sample.yml  docker-compose.yml 

sun@sun-T58-D:~/learn/dnmp-plus$ sudo -s
[sudo] sun 的密码： 

root@sun-T58-D:/home/sun/learn/dnmp-plus# docker-compose up -d php72 nginx mysql

WARNING: The NGINX_VERSION variable is not set. Defaulting to a blank string.
WARNING: The NGINX_HTTP_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The NGINX_HTTPS_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The SOURCE_DIR variable is not set. Defaulting to a blank string.
WARNING: The NGINX_CONFD_DIR variable is not set. Defaulting to a blank string.
WARNING: The NGINX_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The NGINX_LOG_DIR variable is not set. Defaulting to a blank string.
WARNING: The PHP72_VERSION variable is not set. Defaulting to a blank string.
WARNING: The ALPINE_REPOSITORIES variable is not set. Defaulting to a blank string.
WARNING: The PHP72_EXTENSIONS variable is not set. Defaulting to a blank string.
WARNING: The PHP72_PHP_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP72_FPM_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP72_LOG_DIR variable is not set. Defaulting to a blank string.
WARNING: The PHP56_VERSION variable is not set. Defaulting to a blank string.
WARNING: The PHP56_EXTENSIONS variable is not set. Defaulting to a blank string.
WARNING: The PHP56_PHP_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP56_FPM_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP56_LOG_DIR variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_VERSION variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_DATA_DIR variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The REDIS_VERSION variable is not set. Defaulting to a blank string.
WARNING: The REDIS_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDIS_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHPMYADMIN_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDISMYADMIN_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The MONGO_VERSION variable is not set. Defaulting to a blank string.
WARNING: The MONGO_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The MONGO_DATA_DB_DIR variable is not set. Defaulting to a blank string.
WARNING: The MONGO_EXPRESS_HOST_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mongo.ports is invalid: Port ranges don't match in length
services.mysql.ports is invalid: Port ranges don't match in length
services.nginx.ports is invalid: Port ranges don't match in length
services.redis.ports is invalid: Port ranges don't match in length
services.nginx.ports is invalid: Port ranges don't match in length
services.phpmyadmin.ports is invalid: Port ranges don't match in length
services.phpredisadmin.ports is invalid: Port ranges don't match in length
services.mongo-express.ports is invalid: Port ranges don't match in length
root@sun-T58-D:/home/sun/learn/dnmp-plus# 

![image](https://user-images.githubusercontent.com/13595639/92080357-03d03000-edf4-11ea-8cb6-b9eafeaca4d8.png)

**Comment by guanguans** [comment]
@TimeIsGoOn `cp env.sample .env`
