### ISSUE TITLE
install php failed

### ISSUE THREAD

**Issue by gh0sthx** [guanguans/dnmp-plus#18]
![image](https://user-images.githubusercontent.com/19170275/131800757-3d6add36-6300-4f3f-b049-c8c81027cae7.png)
[log.txt](https://github.com/guanguans/dnmp-plus/files/7096906/log.txt)

new question

_Originally posted by @Paladinhanxiao in https://github.com/guanguans/dnmp-plus/issues/17#issuecomment-911310069_

**Comment by gh0sthx** [comment]
the key `make: the '-j' option requires a positive integer argument`

**Comment by Paladinhanxiao** [comment]
你这有问题，dhmp跑起来没问题。

**Comment by guanguans** [comment]
@Paladinhanxiao 

我刚在自己电脑上构建测试了没有问题，通过 travis CI 构建也没有问题，这里是构建具体日志 [travis CI build log](https://app.travis-ci.com/github/guanguans/dnmp-plus/jobs/536106664)，你说的问题我没有复现。

检查一下是按照下面的这个步骤执行的吗：

1. `git clone https://github.com/guanguans/dnmp-plus.git --recursive`
2. `cd dnmp-plus`
3. `cp env.sample .env`
4. `cp docker-compose-sample.yml docker-compose.yml`
5. `docker-compose up -d php72 nginx mysql mongo` (服务选项：nginx、php72、php56、mysql、mongo、redis、phpmyadmin、phpredisadmin、mongo-express)
