### ISSUE TITLE
php7.2 mongodb扩展 不兼容使用

### ISSUE THREAD

**Issue by 544325999** [guanguans/dnmp-plus#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by guanguans** [comment]
@544325999 可否描述的详细一些

**Comment by 544325999** [comment]
xhgui 这个扩展用到mongo php7.2不能直接装mongo  我进去容器手动装了mongo 但是xhgui 里面代码用使用mongo的方式 还是之前mongo扩展方式 7.2版本的不能使用

**Comment by guanguans** [comment]
@544325999 我测试是可以用的，为什么你还要自己再装一个扩展呢

**Comment by 544325999** [comment]
正常安装完我发现是没有mongo扩展的  然后只能去手动安装一个。

**Comment by guanguans** [comment]
env 配置文件里面配置了吗

**Comment by 544325999** [comment]
> env 配置文件里面配置了吗

没有修改过
